### PR TITLE
add `TODO` description in `.js` file.

### PR DESCRIPTION
**Pull request by sheygs**
@topsyLord3, Here's what I want you to do:

- Only disable button when user has not provided an answer, otherwise, enable button

### CODE REVIEW

**Comment by sheygs** [comment]
> @topsyLord3, Here's what I want you to do:
> 
> * Only disable button when user has not provided an answer, otherwise, enable button

@topsyLord3  - disable button by default, only enable the button when the user has provided an option/answer.

**By Default**:
- Disable the button
- Grey out the button/reduce the opacity, color e.t.c 

When an answer is provided:
- Enable the button
- Set the background button to the normal color
- Set the text color to the normal color

**Comment by topsyLord3** [comment]
Have already made the changes u said i should make

**Comment by topsyLord3** [comment]
Have already made the changes u said i should make

**Comment by sheygs13** [comment]
Ok. I will review

**Comment by sheygs** [comment]
> Have already made the changes u said i should make

I can't see the changes to what I told you to work on. Push the changes to GitHub

**Comment by topsyLord3** [comment]
Have already made the changes on github

**Pull request merged**
